-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.talleres (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  contacto text,
  telefono text,
  direccion text,
  notas text,
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT talleres_pkey PRIMARY KEY (id)
);
CREATE TABLE public.repuestos_catalogo (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  codigo text NOT NULL UNIQUE,
  nombre text NOT NULL,
  marca text,
  linea_modelo text,
  anios text,
  precio_ref numeric DEFAULT 0,
  precio_actualizado_at timestamp with time zone DEFAULT now(),
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT repuestos_catalogo_pkey PRIMARY KEY (id)
);
CREATE TABLE public.siniestros (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  numero text NOT NULL DEFAULT ''::text UNIQUE,
  placa text NOT NULL,
  tipo_vehiculo text,
  marca text,
  linea text,
  anio integer,
  odoo_product_id integer,
  contrato_id integer,
  contrato_numero text,
  cliente_nombre text NOT NULL,
  cliente_dpi text,
  cliente_telefono text,
  cliente_email text,
  fecha_dano date NOT NULL,
  lugar_accidente text,
  tipo_dano USER-DEFINED NOT NULL DEFAULT 'otro'::tipo_dano,
  severidad USER-DEFINED NOT NULL DEFAULT 'leve'::severidad_dano,
  descripcion text,
  estado USER-DEFINED NOT NULL DEFAULT 'registrado'::estado_siniestro,
  monto_cliente numeric DEFAULT 0,
  costo_pass numeric DEFAULT 0,
  margen numeric DEFAULT 0,
  taller_id uuid,
  registrado_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cliente_nit text,
  forma_pago USER-DEFINED DEFAULT 'cliente'::forma_pago_dano,
  fecha_entrega_taller date,
  fecha_estimada_entrega date,
  fecha_real_entrega date,
  tiene_prefactura boolean DEFAULT false,
  tiene_proforma boolean DEFAULT false,
  tiene_factura boolean DEFAULT false,
  CONSTRAINT siniestros_pkey PRIMARY KEY (id),
  CONSTRAINT siniestros_taller_id_fkey FOREIGN KEY (taller_id) REFERENCES public.talleres(id),
  CONSTRAINT siniestros_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.cotizaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  siniestro_id uuid NOT NULL,
  taller_id uuid NOT NULL,
  estado USER-DEFINED NOT NULL DEFAULT 'solicitada'::estado_cotizacion,
  fecha_solicitud date DEFAULT CURRENT_DATE,
  fecha_recepcion date,
  total_repuestos numeric DEFAULT 0,
  total_mano_obra numeric DEFAULT 0,
  total_otros numeric DEFAULT 0,
  total_general numeric DEFAULT 0,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  variante text,
  total_descuentos numeric DEFAULT 0,
  CONSTRAINT cotizaciones_pkey PRIMARY KEY (id),
  CONSTRAINT cotizaciones_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT cotizaciones_taller_id_fkey FOREIGN KEY (taller_id) REFERENCES public.talleres(id)
);
CREATE TABLE public.cotizacion_lineas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cotizacion_id uuid NOT NULL,
  tipo USER-DEFINED NOT NULL DEFAULT 'repuesto'::tipo_linea_cotizacion,
  descripcion text NOT NULL,
  repuesto_id uuid,
  cantidad numeric DEFAULT 1,
  precio_unitario numeric DEFAULT 0,
  subtotal numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cotizacion_lineas_pkey PRIMARY KEY (id),
  CONSTRAINT cotizacion_lineas_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES public.cotizaciones(id),
  CONSTRAINT cotizacion_lineas_repuesto_id_fkey FOREIGN KEY (repuesto_id) REFERENCES public.repuestos_catalogo(id)
);
CREATE TABLE public.taller_ingresos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  siniestro_id uuid,
  taller_id uuid NOT NULL,
  fecha_ingreso date NOT NULL DEFAULT CURRENT_DATE,
  fecha_egreso date,
  dias_en_taller integer DEFAULT 0,
  motivo text,
  es_servicio boolean DEFAULT false,
  es_dano boolean DEFAULT true,
  observaciones text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  orden_servicio_id uuid,
  CONSTRAINT taller_ingresos_pkey PRIMARY KEY (id),
  CONSTRAINT taller_ingresos_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT taller_ingresos_taller_id_fkey FOREIGN KEY (taller_id) REFERENCES public.talleres(id),
  CONSTRAINT taller_ingresos_orden_servicio_id_fkey FOREIGN KEY (orden_servicio_id) REFERENCES public.ordenes_servicio(id)
);
CREATE TABLE public.cobros (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  siniestro_id uuid NOT NULL,
  estado USER-DEFINED NOT NULL DEFAULT 'pendiente'::estado_cobro,
  monto_total numeric NOT NULL DEFAULT 0,
  factura_numero text,
  factura_serie text,
  factura_fecha date,
  boleta_pago text,
  fecha_pago date,
  es_gasto_pass boolean DEFAULT false,
  es_seguro boolean DEFAULT false,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cobros_pkey PRIMARY KEY (id),
  CONSTRAINT cobros_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id)
);
CREATE TABLE public.documentos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  siniestro_id uuid,
  cotizacion_id uuid,
  tipo USER-DEFINED NOT NULL DEFAULT 'otro'::tipo_documento,
  nombre_archivo text NOT NULL,
  storage_path text NOT NULL,
  tamanio_bytes bigint,
  mime_type text,
  subido_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  orden_servicio_id uuid,
  CONSTRAINT documentos_pkey PRIMARY KEY (id),
  CONSTRAINT documentos_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT documentos_cotizacion_id_fkey FOREIGN KEY (cotizacion_id) REFERENCES public.cotizaciones(id),
  CONSTRAINT documentos_subido_por_fkey FOREIGN KEY (subido_por) REFERENCES auth.users(id),
  CONSTRAINT documentos_orden_servicio_id_fkey FOREIGN KEY (orden_servicio_id) REFERENCES public.ordenes_servicio(id)
);
CREATE TABLE public.siniestro_timeline (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  siniestro_id uuid NOT NULL,
  estado_anterior USER-DEFINED,
  estado_nuevo USER-DEFINED NOT NULL,
  accion text NOT NULL,
  detalle text,
  usuario_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT siniestro_timeline_pkey PRIMARY KEY (id),
  CONSTRAINT siniestro_timeline_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT siniestro_timeline_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id)
);
CREATE TABLE public.perfiles (
  id uuid NOT NULL,
  nombre_completo text NOT NULL,
  rol text NOT NULL DEFAULT 'agente'::text CHECK (rol = ANY (ARRAY['admin'::text, 'agente_senior'::text, 'agente'::text, 'operaciones'::text, 'readonly'::text])),
  activo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  permisos jsonb DEFAULT '{"ver": true, "crear": false, "editar": false, "eliminar": false}'::jsonb,
  CONSTRAINT perfiles_pkey PRIMARY KEY (id),
  CONSTRAINT perfiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.ordenes_servicio (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  numero text NOT NULL DEFAULT ''::text UNIQUE,
  placa text NOT NULL,
  tipo_vehiculo text,
  marca text,
  linea text,
  anio integer,
  odoo_product_id integer,
  tipo_servicio USER-DEFINED NOT NULL DEFAULT 'otro'::tipo_servicio_mant,
  descripcion text,
  fecha_programada date,
  kilometraje integer,
  estado USER-DEFINED NOT NULL DEFAULT 'programado'::estado_orden_servicio,
  requiere_autorizacion boolean DEFAULT false,
  autorizado_por text,
  fecha_autorizacion date,
  taller_id uuid,
  total_repuestos numeric DEFAULT 0,
  total_mano_obra numeric DEFAULT 0,
  total_otros numeric DEFAULT 0,
  total_general numeric DEFAULT 0,
  registrado_por uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  fecha_entrega_taller date,
  fecha_estimada_entrega date,
  fecha_real_entrega date,
  total_descuentos numeric DEFAULT 0,
  tiene_prefactura boolean DEFAULT false,
  tiene_proforma boolean DEFAULT false,
  tiene_factura boolean DEFAULT false,
  CONSTRAINT ordenes_servicio_pkey PRIMARY KEY (id),
  CONSTRAINT ordenes_servicio_taller_id_fkey FOREIGN KEY (taller_id) REFERENCES public.talleres(id),
  CONSTRAINT ordenes_servicio_registrado_por_fkey FOREIGN KEY (registrado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.orden_servicio_lineas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  orden_servicio_id uuid NOT NULL,
  tipo USER-DEFINED NOT NULL DEFAULT 'repuesto'::tipo_linea_cotizacion,
  descripcion text NOT NULL,
  repuesto_id uuid,
  cantidad numeric DEFAULT 1,
  precio_unitario numeric DEFAULT 0,
  subtotal numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orden_servicio_lineas_pkey PRIMARY KEY (id),
  CONSTRAINT orden_servicio_lineas_orden_servicio_id_fkey FOREIGN KEY (orden_servicio_id) REFERENCES public.ordenes_servicio(id),
  CONSTRAINT orden_servicio_lineas_repuesto_id_fkey FOREIGN KEY (repuesto_id) REFERENCES public.repuestos_catalogo(id)
);
CREATE TABLE public.orden_servicio_timeline (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  orden_servicio_id uuid NOT NULL,
  estado_anterior USER-DEFINED,
  estado_nuevo USER-DEFINED NOT NULL,
  accion text NOT NULL,
  detalle text,
  usuario_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orden_servicio_timeline_pkey PRIMARY KEY (id),
  CONSTRAINT orden_servicio_timeline_orden_servicio_id_fkey FOREIGN KEY (orden_servicio_id) REFERENCES public.ordenes_servicio(id),
  CONSTRAINT orden_servicio_timeline_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tabla text NOT NULL,
  fila_id uuid NOT NULL,
  operacion text NOT NULL CHECK (operacion = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  campo text,
  valor_anterior jsonb,
  valor_nuevo jsonb,
  usuario_id uuid,
  usuario_email text,
  contexto jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id)
);
CREATE TABLE public.taller_contactos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  taller_id uuid NOT NULL,
  nombre text NOT NULL,
  puesto text,
  area USER-DEFINED NOT NULL DEFAULT 'taller'::area_contacto,
  telefono text,
  whatsapp text,
  email text,
  es_principal boolean DEFAULT false,
  activo boolean DEFAULT true,
  notas text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT taller_contactos_pkey PRIMARY KEY (id),
  CONSTRAINT taller_contactos_taller_id_fkey FOREIGN KEY (taller_id) REFERENCES public.talleres(id)
);
CREATE TABLE public.bitacora_actualizaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  siniestro_id uuid,
  orden_servicio_id uuid,
  nota text NOT NULL CHECK (length(TRIM(BOTH FROM nota)) > 0),
  usuario_id uuid,
  usuario_email text,
  usuario_nombre text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bitacora_actualizaciones_pkey PRIMARY KEY (id),
  CONSTRAINT bitacora_actualizaciones_siniestro_id_fkey FOREIGN KEY (siniestro_id) REFERENCES public.siniestros(id),
  CONSTRAINT bitacora_actualizaciones_orden_servicio_id_fkey FOREIGN KEY (orden_servicio_id) REFERENCES public.ordenes_servicio(id),
  CONSTRAINT bitacora_actualizaciones_usuario_id_fkey FOREIGN KEY (usuario_id) REFERENCES auth.users(id)
);